services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    depends_on:
      - php
    networks:
      - symfony
    ports:
      - "80:80"

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
  app-network:
      driver: bridge

 
volumes:
  redis_volume_data:
  